/* this file contains the definition of the CGI class.
 * It gets an input in case of post, runs a CGI script
 *  with a specified executable and writes the output to a file.
 * The input and output files should be set before
 *  the CGI is run.
 * All the other necessary information will be retrieved
 *  from the request object that's passed to its constructor
 */

#pragma once

#include <Request.hpp>
#include <StatusCodeHandler.hpp>
#include <unistd.h>
#include <sys/wait.h>
#include <signal.h>
#include <fcntl.h>
#include <stdlib.h>

class CGI {

	public:
		/******* alias types *******/
		typedef Request::Method Method;
		typedef StatusCodeHandler::StatusCodeType
			StatusCodeType;
		typedef Config::CGISystems CGISystems;
		typedef Request::HeaderValue HeaderValue;

		/******* public member functions *******/
		CGI(const Request& request);

		void setInputFilePath(const std::string& path);

		void setOutputFilePath(const std::string& path);

		void run();

		// was the cgi run correctly
		bool isValid();

		StatusCodeType getStatusCode();

		// gets the content length of the body
			// that is generated by the script 
		size_t getContentLength();
	
	private:
		/******* private member objects *******/
		// the file path from which the CGI
			// gets its input (request body)
		// if the method is not GET, then there
			// is no input
		std::string mInputFilePath;

		// the filepath where the cgi script
			// will save its output
		std::string mOutputFilePath;

		StatusCodeType mStatusCode;

		size_t mContentLength;

		// the full path of the cgi script
			// to be executed
		const std::string& mScriptPath;

		const Request& mRequest;
	
		// after the script is executed
			// it will time out if it takes 
			// more than this time
		// this time is expressed in seconds
		static const int mWaitTime;

		/******* private member functions *******/
		// runs the executable as a child process, calls
			// the functions that prepare the script's environment
			// and waits for its termination
		// sets the status code to an error code if
			// an error happens (e.g. couldn't execute)
		void manageExecution();

		// waits for the script to execute for a defined
			// amount of time. if it takes more, then the script
			// times out and status code is set accordingly
		// takes the process id of the executed script
		void waitForScript(const pid_t pid);

		// sets the script to read its input from mInputFilePath
			// in case of POST request Method
			// and to write its output to mOutputFilePath
		// if IO couldn't be set, status code is set accordinly
		// throws std::runtime_error in case of error
		void setScriptIO();

		// finds the executable set in the configured
			// location
		// throws std::runtime_error in case no
			// executable was found
		const std::string& findExecutable();

		// sets the environment variables needed
			// for the CGI to run properly
		// sets status code to an error code
			// and throws std::runtime_error 
			// in case of error
		void setEnv();

		// sets the content length of the body
			// that is generated by the script
		// throws std::runtime_error in case
			// the content length could'nt be determined
		void setContentLength();

};
